/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Earning {
  'id' : bigint,
  'month' : bigint,
  'year' : bigint,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface Expense {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addExpense' : ActorMethod<[bigint, string, string, Time], bigint>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByMonthYear' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getMonthlyEarnings' : ActorMethod<[bigint, bigint], [] | [Earning]>,
  'getMonthlySavings' : ActorMethod<[bigint, bigint], bigint>,
  'getTotalExpensesByCategory' : ActorMethod<[string, bigint, bigint], bigint>,
  'setMonthlyEarnings' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'updateExpense' : ActorMethod<
    [bigint, bigint, string, string, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];