/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Earning = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Time], [IDL.Nat], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getMonthlyEarnings' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(Earning)],
      ['query'],
    ),
  'getMonthlySavings' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getTotalExpensesByCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'setMonthlyEarnings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Earning = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Time], [IDL.Nat], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getMonthlyEarnings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(Earning)],
        ['query'],
      ),
    'getMonthlySavings' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getTotalExpensesByCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'setMonthlyEarnings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };